// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherProject.Models;

namespace WeatherProject.Migrations.WeatherDB
{
    [DbContext(typeof(WeatherDBContext))]
    partial class WeatherDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherProject.Models.ViewModels.WeatherViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AIR_PRESSURE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AIR_QUALITY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AMBIENT_TEMPERATURE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GROUND_TEMPERATURE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HUMIDITY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RAINFALL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WIND_DIRECTION")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WIND_GUST_SPEED")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WIND_SPEED")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
